# Generated by Django 5.0 on 2023-12-30 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('nombreUsuario', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=10)),
                ('correoElectronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaInventory.registrousuario')),
            ],
        ),
        migrations.CreateModel(
            name='EncargadosVentas',
            fields=[
                ('id_encargadoVenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('encargadoVenta', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaInventory.registrousuario')),
            ],
        ),
        migrations.CreateModel(
            name='EncargadosCompras',
            fields=[
                ('id_encargadoCompra', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('encargadoCompra', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaInventory.registrousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('horaCompra', models.TimeField(max_length=8)),
                ('fechaCompra', models.DateField(auto_now_add=True)),
                ('encargadoCompra', models.CharField(max_length=50)),
                ('suplidor', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('itbis', models.IntegerField()),
                ('costo', models.IntegerField()),
                ('totalCompra', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaInventory.registrousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=11)),
                ('correoElectronico', models.EmailField(max_length=254)),
                ('rnc', models.IntegerField()),
                ('descuento', models.CharField(max_length=4)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaInventory.registrousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=80)),
                ('ubicacion', models.CharField(max_length=20)),
                ('costo', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('itbis', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('unidadMedida', models.CharField(max_length=8)),
                ('margenBeneficio', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaInventory.registrousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Suplidores',
            fields=[
                ('id_suplidor', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('limiteCredito', models.CharField(max_length=11)),
                ('condiciones', models.CharField(max_length=50)),
                ('rnc', models.IntegerField()),
                ('descuento', models.CharField(max_length=4)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaInventory.registrousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('horaVenta', models.TimeField(max_length=8)),
                ('fechaVenta', models.DateField(auto_now_add=True)),
                ('encargadoVenta', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('itbis', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('totalVenta', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaInventory.registrousuario')),
            ],
        ),
    ]
